AllCops:
  NewCops: enable
  Exclude:
    - db/**
    - db/**/*
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake}'
    - 'app/views/**/*'
    - '**/*.jbuilder'
  # RunRailsCops: true

Metrics/AbcSize:
  Enabled: false
  Max: 50

Metrics/MethodLength:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: true

Naming/InclusiveLanguage:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Enabled: false
  Max: 200
